(() => {
  const DATA = window.DASHBOARD_DATA;
  const $ = (id) => document.getElementById(id);
  const colors = ['#176b70','#e96f42','#3768a5','#d6a335','#7655a5','#6f7d4e','#a65154'];
  const state = { event:'', course:'', period:'', sex:'', topic:'', search:'', selectedAnswer:null };
  const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fold = (s='') => String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const countBy = (items, fn) => Object.entries(items.reduce((a,x)=>{const k=fn(x);if(k!==null&&k!==undefined&&k!=='')a[k]=(a[k]||0)+1;return a;},{})).sort((a,b)=>b[1]-a[1]);
  const pct = (n,d) => d ? `${Math.round(n/d*100)}%` : '—';

  function filteredRecords(){
    return DATA.registros.filter(r => {
      const answers = r.respostas || [];
      const hay = fold(answers.map(a=>a.resposta).join(' '));
      const topics = new Set(answers.flatMap(a=>a.temas));
      return (!state.event||r.evento===state.event)&&(!state.course||r.curso===state.course)&&(!state.period||String(r.periodo)===state.period)&&(!state.sex||r.sexo===state.sex)&&(!state.topic||topics.has(state.topic))&&(!state.search||hay.includes(fold(state.search)));
    });
  }
  function filteredAnswers(records){const ids=new Set(records.map(r=>r.id));return DATA.respostas.filter(a=>ids.has(a.id_resposta)&&(!state.topic||a.temas.includes(state.topic))&&(!state.search||fold(a.resposta).includes(fold(state.search))));}
  function fillSelect(id, values){const el=$(id);values.filter(Boolean).sort((a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true})).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=id==='filterPeriod'?`${v}º período`:v;el.appendChild(o);});}
  function bars(id, entries, opts={}){const el=$(id);const max=Math.max(...entries.map(x=>x[1]),1);el.innerHTML=entries.length?entries.map(([label,value],i)=>`<div class="bar-row ${opts.click?'clickable':''}" ${opts.click?`data-value="${esc(label)}"`:''}><span class="bar-label" title="${esc(label)}">${esc(label)}</span><div class="bar-track"><div class="bar-fill" style="width:${value/max*100}%;background:${opts.color||colors[i%colors.length]}"></div></div><strong class="bar-value">${value}</strong></div>`).join(''):'<div class="empty">Sem dados para a seleção.</div>';
    if(opts.click) el.querySelectorAll('[data-value]').forEach(node=>node.onclick=()=>{state[opts.click]=node.dataset.value;syncInputs();render();});
  }
  function donut(id, entries){const total=entries.reduce((s,x)=>s+x[1],0);let offset=0;const circles=entries.map(([label,n],i)=>{const len=total?n/total*100:0;const c=`<circle cx="65" cy="65" r="48" stroke="${colors[i%colors.length]}" stroke-dasharray="${len} ${100-len}" stroke-dashoffset="-${offset}" pathLength="100"/>`;offset+=len;return c;}).join('');$(id).innerHTML=`<div class="donut"><svg viewBox="0 0 130 130" role="img" aria-label="Distribuição"><circle class="base" cx="65" cy="65" r="48"/><g>${circles}</g></svg><div class="legend">${entries.map(([l,n],i)=>`<div class="legend-item"><i class="dot" style="background:${colors[i%colors.length]}"></i><span>${esc(l)}</span><strong>${pct(n,total)}</strong></div>`).join('')}</div></div>`;}
  function renderMatrix(answers){const events=[...new Set(DATA.registros.map(r=>r.evento))];const head=$('topicMatrix').querySelector('thead'),body=$('topicMatrix').querySelector('tbody');head.innerHTML=`<tr><th>Tema</th>${events.map(e=>`<th>${esc(e)}</th>`).join('')}<th>Total</th></tr>`;const max=Math.max(...DATA.temas.map(t=>answers.filter(a=>a.temas.includes(t)).length),1);body.innerHTML=DATA.temas.map(t=>{const values=events.map(e=>answers.filter(a=>a.evento===e&&a.temas.includes(t)).length);const total=values.reduce((a,b)=>a+b,0);return `<tr><td><strong>${esc(t)}</strong></td>${values.map(v=>`<td class="matrix-cell" style="background:rgba(23,107,112,${.06+.32*v/max})">${v}</td>`).join('')}<td><strong>${total}</strong></td></tr>`;}).join('');}
  function renderAnswers(records,answers){$('answerCount').textContent=`${answers.length} resultados`;$('answerList').innerHTML=answers.length?answers.map((a,i)=>{const r=records.find(x=>x.id===a.id_resposta);return `<article class="answer-card ${state.selectedAnswer===i?'active':''}" data-answer="${i}"><header><span>${esc(a.evento)}</span><span>${esc(r?.curso||'')}</span></header><h4>${esc(a.pergunta)}</h4><p>${esc(a.resposta)}</p><div class="chips">${a.temas.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div></article>`;}).join(''):'<div class="empty">Nenhuma resposta corresponde aos filtros.</div>';
    $('answerList').querySelectorAll('[data-answer]').forEach(n=>n.onclick=()=>{state.selectedAnswer=Number(n.dataset.answer);renderAnswers(records,answers);});
    const a=answers[state.selectedAnswer];const r=a&&records.find(x=>x.id===a.id_resposta);$('answerDetail').innerHTML=a?`<span class="eyebrow">${esc(a.evento)}</span><h3>${esc(a.pergunta)}</h3><blockquote>“${esc(a.resposta)}”</blockquote><div class="chips">${a.temas.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><div class="meta"><span>${esc(r.curso)}</span><span>${r.periodo?`${r.periodo}º período`:'Período não informado'}</span><span>${r.id}</span></div>`:'<p>Selecione uma resposta para ler o conteúdo completo.</p>';
  }
  function renderTranscript(){const speaker=$('speakerFilter').value,q=fold($('speechSearch').value);const rows=DATA.transcricao.filter(s=>(!speaker||s.participante===speaker)&&(!q||fold(s.fala).includes(q)));$('transcriptList').innerHTML=rows.length?rows.map(s=>`<article class="speech"><strong>${esc(s.participante)}</strong><time>#${s.ordem}</time><div><p>${esc(s.fala)}</p><div class="chips">${s.temas.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div></div></article>`).join(''):'<div class="empty">Nenhuma fala encontrada.</div>';}
  function renderFilterAI(records,answers){
    const active=[state.event,state.course,state.period?`${state.period}º período`:'',state.sex,state.topic,state.search?`busca “${state.search}”`:''].filter(Boolean);
    $('aiFilterLabel').textContent=active.length?active.join(' · '):'Todos os dados';
    if(!records.length||!answers.length){$('aiFilterContext').textContent='A seleção atual não possui respostas suficientes para produzir uma interpretação.';$('aiFilterQuestions').innerHTML='';$('aiFilterCaution').textContent='Altere ou remova algum filtro para ampliar a seleção.';return;}
    const themeCounts=Object.fromEntries(countBy(answers.flatMap(a=>a.temas),x=>x));
    const totalCounts=Object.fromEntries(countBy(DATA.respostas.flatMap(a=>a.temas),x=>x));
    const themeRows=DATA.temas.map(t=>({theme:t,count:themeCounts[t]||0,rate:(themeCounts[t]||0)/answers.length,totalRate:(totalCounts[t]||0)/DATA.respostas.length})).sort((a,b)=>b.rate-a.rate);
    const top=themeRows.slice(0,3),rising=[...themeRows].sort((a,b)=>(b.rate-b.totalRate)-(a.rate-a.totalRate))[0],falling=[...themeRows].sort((a,b)=>(a.rate-a.totalRate)-(b.rate-b.totalRate))[0];
    const courses=countBy(records,r=>r.curso),sexes=countBy(records,r=>r.sexo),periods=countBy(records,r=>r.periodo?`${r.periodo}º período`:'período não informado');
    const education=['Educação','Acessibilidade','Direitos','Igualdade','Respeito'].map(t=>themeRows.find(x=>x.theme===t)).filter(x=>x&&x.count).sort((a,b)=>b.rate-a.rate);
    const possibilityMap={Educação:'adaptação das práticas e atenção ao processo de aprendizagem',Acessibilidade:'remoção de barreiras e garantia de acessibilidade',Direitos:'garantia de direitos e participação',Igualdade:'igualdade de oportunidades com atenção às necessidades',Respeito:'acolhimento e valorização das diferenças'};
    const scope=active.length?`Com os filtros ${active.join(', ')}, permanecem ${records.length} participantes e ${answers.length} respostas abertas.`:`O conjunto completo reúne ${records.length} participantes e ${answers.length} respostas abertas.`;
    $('aiFilterContext').textContent=`${scope} A leitura abaixo compara proporcionalmente essa seleção com o corpus completo.`;
    const emphasis=rising.rate-rising.totalRate;const fall=falling.totalRate-falling.rate;
    const questions=[
      ['Quem fica representado?',`Predomina o curso <strong>${esc(courses[0]?.[0]||'não informado')}</strong> (${pct(courses[0]?.[1]||0,records.length)}), com maior presença de <strong>${esc(sexes[0]?.[0]||'sexo não informado')}</strong> (${pct(sexes[0]?.[1]||0,records.length)}) e de <strong>${esc(periods[0]?.[0]||'período não informado')}</strong> (${pct(periods[0]?.[1]||0,records.length)}).`],
      ['Quais concepções ganham destaque?',`Os temas mais presentes são <strong>${top.map(x=>`${esc(x.theme)} (${Math.round(x.rate*100)}%)`).join(', ')}</strong>. Isso sugere que a inclusão está sendo compreendida sobretudo por essas dimensões na seleção atual.`],
      ['O que muda em relação ao conjunto total?',emphasis>.025?`<strong>${esc(rising.theme)}</strong> ganha ${Math.round(emphasis*100)} pontos percentuais de ênfase. ${fall>.025?`Já <strong>${esc(falling.theme)}</strong> aparece ${Math.round(fall*100)} pontos abaixo do conjunto completo.`:'Os demais temas permanecem próximos do padrão geral.'}`:'A distribuição temática permanece próxima do conjunto completo; o filtro altera mais quem está representado do que o sentido geral das respostas.'],
      ['Que possibilidades educacionais aparecem?',education.length?`A seleção sustenta principalmente: <strong>${education.slice(0,3).map(x=>possibilityMap[x.theme]).join('; ')}</strong>. Essa é uma inferência temática, não uma recomendação atribuída literalmente a cada participante.`:'A seleção não reúne menções suficientes aos eixos educacionais mapeados para formular uma hipótese segura.']
    ];
    $('aiFilterQuestions').innerHTML=questions.map(([q,a])=>`<article class="filter-ai-answer"><h4>${q}</h4><p>${a}</p></article>`).join('');
    $('aiFilterCaution').textContent=records.length<10?'Atenção: seleção com menos de 10 participantes. As variações podem refletir poucos casos e devem ser lidas apenas como pistas exploratórias.':'Conteúdo gerado por IA a partir de frequências e associações temáticas automáticas. Use como apoio exploratório e valide com a leitura das respostas originais.';
  }
  function render(){const records=filteredRecords(),answers=filteredAnswers(records),ages=records.map(r=>r.idade).filter(Number.isFinite);$('kpiRecords').textContent=records.length;$('kpiAnswers').textContent=answers.length;$('kpiAge').textContent=ages.length?(ages.reduce((a,b)=>a+b,0)/ages.length).toFixed(1).replace('.',','):'—';$('kpiWork').textContent=pct(records.filter(r=>r.atua_profissionalmente==='Sim').length,records.length);const ids=new Set(records.map(r=>r.id));const issues=DATA.inconsistencias.filter(i=>ids.has(i.id_resposta));$('kpiIssues').textContent=issues.length;$('filterSummary').textContent=records.length===DATA.registros.length?'Todos os registros':`${records.length} de ${DATA.registros.length} registros`;
    bars('eventChart',countBy(records,r=>r.evento),{click:'event'});bars('timelineChart',countBy(records,r=>r.data).sort((a,b)=>a[0].localeCompare(b[0])),{color:'#3768a5'});
    bars('ageChart',countBy(records,r=>r.idade<20?'Até 19':r.idade<25?'20–24':r.idade<30?'25–29':r.idade?'30 ou mais':null),{color:'#d6a335'});donut('sexChart',countBy(records,r=>r.sexo));bars('periodChart',countBy(records,r=>r.periodo?`${r.periodo}º`:'Não informado'),{color:'#7655a5'});bars('courseChart',countBy(records,r=>r.curso).slice(0,12),{color:'#176b70'});
    bars('topicChart',countBy(answers.flatMap(a=>a.temas),x=>x),{click:'topic'});const maxWord=Math.max(...DATA.palavras.map(w=>w.frequencia),1);$('wordCloud').innerHTML=DATA.palavras.slice(0,30).map(w=>`<button style="font-size:${12+22*w.frequencia/maxWord}px" data-word="${esc(w.palavra)}">${esc(w.palavra)}</button>`).join('');$('wordCloud').querySelectorAll('[data-word]').forEach(n=>n.onclick=()=>{state.search=n.dataset.word;syncInputs();render();});renderMatrix(answers);renderAnswers(records,answers);renderFilterAI(records,answers);bars('issueChart',countBy(issues,i=>i.campo),{color:'#e96f42'});$('issueCount').textContent=`${issues.length} itens`;
  }
  function syncInputs(){$('filterEvent').value=state.event;$('filterCourse').value=state.course;$('filterPeriod').value=state.period;$('filterSex').value=state.sex;$('filterTopic').value=state.topic;$('filterSearch').value=state.search;}
  function exportCsv(){const records=filteredRecords();const headers=['id','evento','data','idade','sexo','curso','periodo','atua_profissionalmente','ocupacao'];const lines=[headers.join(';'),...records.map(r=>headers.map(h=>`"${String(r[h]??'').replaceAll('"','""')}"`).join(';'))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='selecao_dashboard.csv';a.click();URL.revokeObjectURL(a.href);}
  fillSelect('filterEvent',[...new Set(DATA.registros.map(r=>r.evento))]);fillSelect('filterCourse',[...new Set(DATA.registros.map(r=>r.curso))]);fillSelect('filterPeriod',[...new Set(DATA.registros.map(r=>r.periodo).filter(Boolean).map(String))]);fillSelect('filterSex',[...new Set(DATA.registros.map(r=>r.sexo))]);fillSelect('filterTopic',DATA.temas);fillSelect('speakerFilter',[...new Set(DATA.transcricao.map(s=>s.participante))]);
  [['filterEvent','event'],['filterCourse','course'],['filterPeriod','period'],['filterSex','sex'],['filterTopic','topic']].forEach(([id,k])=>$(id).onchange=e=>{state[k]=e.target.value;state.selectedAnswer=null;render();});$('filterSearch').oninput=e=>{state.search=e.target.value;state.selectedAnswer=null;render();};$('clearFilters').onclick=()=>{Object.assign(state,{event:'',course:'',period:'',sex:'',topic:'',search:'',selectedAnswer:null});syncInputs();render();};$('speakerFilter').onchange=renderTranscript;$('speechSearch').oninput=renderTranscript;$('exportBtn').onclick=exportCsv;
  const ai=DATA.interpretacao_ia;$('aiThesis').textContent=ai.tese;$('aiReadings').innerHTML=ai.leituras.map((item,i)=>`<article class="ai-card"><header><span class="ai-index">0${i+1}</span><h3>${esc(item.titulo)}</h3></header><p>${esc(item.texto)}</p><p class="ai-evidence"><strong>Evidência nos dados</strong>${esc(item.evidencia)}</p></article>`).join('');$('aiSummary').textContent=ai.sintese;$('aiLimits').innerHTML=ai.limites.map(x=>`<li>${esc(x)}</li>`).join('');$('aiReferences').innerHTML=ai.referencias.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">${esc(x.titulo)}</a>`).join('');
  $('updatedAt').textContent=new Date(DATA.gerado_em).toLocaleString('pt-BR');$('sourceList').innerHTML=DATA.manifesto.map(s=>`<div class="source"><strong>${esc(s.arquivo)}</strong><span>${s.tamanho_bytes.toLocaleString('pt-BR')} bytes · SHA-256 ${esc(s.sha256.slice(0,16))}…</span></div>`).join('');$('mappingTable').querySelector('tbody').innerHTML=DATA.normalizacoes.slice(0,150).map(m=>`<tr><td>${esc(m.campo)}</td><td>${esc(m.valor_original)}</td><td><strong>${esc(m.valor_tratado||'Revisar')}</strong></td><td>${esc(m.regra)}</td></tr>`).join('');
  renderTranscript();render();
})();
